import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""
app_ad5933.c
drv_ad5933.c
hmi.c
main.c
onenet_service.c
tgam.c
upload.c
wifi.c
""")

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
